name = "MyPhD"
uuid = "edc1bba5-429e-478a-b473-2a5b77802cb0"
authors = ["ajstaat <alst0620@colorado.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
